## https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml
##
Documentation:
  Enabled: false

require: rubocop-performance

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'  
    - 'lib/**/*'  
    - 'bin/**/*'
    - 'tmp/**'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'Guardfile'
    - 'Rakefile'

Metrics:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
