language: ruby
script: true
os: linux

cache:
  bundler: true
  directories:
    - vendor/

before_install:
  - bin/ci/configure-coveralls
  - mkdir -p app/assets/images
  - bundle config set path 'vendor/cache'

install:
  - gem install bundler
  - bundle install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod 700 ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rake
  - bundle exec rubocop

after_success:
  - ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code 0
